package form

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/OpenNSW/nsw/internal/form/model"
	"gorm.io/gorm"
)

// SeedForms loads example forms from JSON files into the database
// This is useful for development and testing
func SeedForms(db *gorm.DB, examplesDir string) error {
	exampleFiles := []string{
		"customs_declaration.json",
		"tea_permit.json",
		"oga_review.json",
	}

	for _, filename := range exampleFiles {
		filePath := filepath.Join(examplesDir, filename)
		data, err := os.ReadFile(filePath)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", filename, err)
		}

		var formData struct {
			FormID      string          `json:"formId"` // Ignored, kept for JSON compatibility
			Name        string          `json:"name"`
			Description string          `json:"description"`
			Version     string          `json:"version"`
			Schema      json.RawMessage `json:"schema"`
			UISchema    json.RawMessage `json:"uiSchema"`
		}

		if err := json.Unmarshal(data, &formData); err != nil {
			return fmt.Errorf("failed to parse %s: %w", filename, err)
		}

		// Check if form already exists by name
		var existingForm model.Form
		result := db.Where("name = ?", formData.Name).First(&existingForm)
		if result.Error == nil {
			// Form exists, skip
			continue
		}
		if !errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return fmt.Errorf("failed to check existing form %s: %w", formData.Name, result.Error)
		}

		// Create new form (ID will be auto-generated by BaseModel)
		form := model.Form{
			Name:        formData.Name,
			Description: formData.Description,
			Version:     formData.Version,
			Schema:      formData.Schema,
			UISchema:    formData.UISchema,
			Active:      true,
		}

		if err := db.Create(&form).Error; err != nil {
			return fmt.Errorf("failed to create form %s: %w", formData.Name, err)
		}
	}

	return nil
}
